name: 'Syntax:Lab1'
description: 'Action of Lab1 in Syntax section'
inputs:
  say:
    description: 'The text to say'
    required: true
  eyes:
    description: 'The eyes to use'
    required: false
    default: 'oo'
runs:
  using: 'docker'
  image: 'docker://rancher/cowsay:latest'
  args:
    - '-e'
    - '${{ inputs.eyes }}'
    - '${{ inputs.say }}'
