name: LAB3
on: 
  workflow_dispatch:
jobs:
  test-interactions-lab1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run prepare
      - uses: ./.github/actions/lab3