name: LAB4
on: 
  workflow_dispatch:
jobs:
  test-testing-lab1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: bats test
        run: |
          echo "run test..."
        shell: bash