name: LAB4
on: 
  workflow_dispatch:
jobs:
  test-testing-lab1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: load submodules
        run: |
          git submodule update --init --recursive
      - name: bats test
        run: |
          echo "run test..."
          tests/bats/bin/bats tests/lab-tests.bats
        shell: bash