name: LAB5
on: pull_request
jobs:
  check-section:
    strategy:
        matrix:
            directory: [ 'docs/section1', 'docs/section2', 'docs/section3', 'docs/section4' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set directory
        env:
          DIR: ${{ matrix.directory }}
        run: |
          echo "DIRECTORY=${DIR}" >> $GITHUB_ENV
        shell: bash

      - name: Linter installation
        run: |
          npm install -g markdownlint-cli
        shell: bash

      - name: Print markdownlint version
        run: |
          echo $(markdownlint -V)
        shell: bash

      - name: Lint the section markdown
        continue-on-error: true
        run: |
          markdownlint ${{ env.DIRECTORY }}/*.md -o tmp.txt
        shell: bash
 
      - name: Format result
        id: format-result
        uses: actions/github-script@v7
        with:
          github-token: $GITHUB_TOKEN
          result-encoding: string
          script: |
            const fs = require('fs').promises;
            var reportBulk = (await fs.readFile("tmp.txt")).toString();
            const output = `### Lint 📖
            <details>
            \`\`\`
            `+reportBulk+`
            \`\`\`
            </details>`
            return output;

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: ${{ env.DIRECTORY }}

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ${{ env.DIRECTORY }}
            ${{ steps.format-result.outputs.result }}

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ## ${{ env.DIRECTORY }}
            ${{ steps.format-result.outputs.result }}
          edit-mode: replace
  
permissions: write-all