name: LAB5
on: pull_request
jobs:
  check-section1:
    permissions: write-all
    strategy:
      matrix:
        dir:
          - docs/section1
          - docs/section2
          - docs/section3
          - docs/section4
    uses: ./.github/workflows/lab5_reusablewf.yaml
    with:
      dir: ${{ matrix.dir }}